### PR TITLE
Fixed tooltip text clipping

### LINKED ISSUE #15: Text that should appear below tooltip clips in front of it
Image

### PR DESCRIPTION
**Pull request by rhit-steineig**
This PR updates the tooltip alignment in InfoToolTip.svelte to fix #15 (and also happens to serve as a better fix for #73 than #137)

### CODE REVIEW

File: src/lib/components/InfoToolTip.svelte [hunk 1]
```diff
@@ -1,19 +1,31 @@
...
+		tooltipAlignment = centerX < viewportWidth / 2 ? "left" : "right";
+	}
 </script>
 
-<div class="relative group inline-block">
+<div
+	class="relative group inline-block"
+	bind:this={tooltipContainer}
+	onmouseenter={updateAlignment}
+	role="tooltip">
```
Comment (1FoxInTheBox1) [inline src/lib/components/InfoToolTip.svelte]: What's up with this `role` tag? Is it necessary for this fix or just good practice?

**Review by 1FoxInTheBox1 — APPROVED** [review]
LGTM, just a quick question. Not a blocker though! Good work!

File: src/lib/components/InfoToolTip.svelte (hunk 1 above)
Comment (rhit-steineig) [reply src/lib/components/InfoToolTip.svelte]: It's just good practice for accessibility
